spring.application.name=springbootcrud

# database configretion 

spring.datasource.url=jdbc:mysql://localhost:3306/crud_db
spring.datasource.username = root
spring.datasource.password = root


# hibernet confogretion

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

